-- 코드를 작성해주세요
select
    CASE 
    WHEN MONTH(DIFFERENTIATION_DATE) < 4 THEN '1Q'
    WHEN MONTH(DIFFERENTIATION_DATE) < 7 THEN '2Q'
    WHEN MONTH(DIFFERENTIATION_DATE) < 10 THEN '3Q'
    ELSE '4Q'
    END as 'QUARTER',
    count(*) as ECOLI_COUNT
from ECOLI_DATA ed
group by
    CASE 
    WHEN MONTH(DIFFERENTIATION_DATE) < 4 THEN '1Q'
    WHEN MONTH(DIFFERENTIATION_DATE) < 7 THEN '2Q'
    WHEN MONTH(DIFFERENTIATION_DATE) < 10 THEN '3Q'
    ELSE '4Q'
    END
order by
    CASE 
    WHEN MONTH(DIFFERENTIATION_DATE) < 4 THEN '1Q'
    WHEN MONTH(DIFFERENTIATION_DATE) < 7 THEN '2Q'
    WHEN MONTH(DIFFERENTIATION_DATE) < 10 THEN '3Q'
    ELSE '4Q'
    END ASC
